// <auto-generated />
using System;
using EmployeeValueEvaluation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeValueEvaluation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909113700_InitialEmployeeEvaluation2")]
    partial class InitialEmployeeEvaluation2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeValueEvaluation.Models.CorrectionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdjustedBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CorrectionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CorrectionROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Probability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetScore")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CorrectionPlans");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonnelCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelCode")
                        .IsUnique()
                        .HasFilter("[PersonnelCode] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.MonthlyEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BCR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Communication")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Compliance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Documentation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EconomicScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FairSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalValueScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("NetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Performance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotentialValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProblemSolving")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Productivity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quality")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ROI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RiskFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SVR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Timeliness")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValueGap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyEvaluations");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.SalaryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryHistories");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdjustedBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("LossAvoidance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RevenueBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StrategicBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId")
                        .IsUnique();

                    b.ToTable("TaskBenefits");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DelayCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmployeeHoursCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExternalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ManagerHoursCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpportunityCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReworkCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RiskCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId")
                        .IsUnique();

                    b.ToTable("TaskCosts");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BugCount")
                        .HasColumnType("int");

                    b.Property<decimal>("CommunicationScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ComplianceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CriticalBugCount")
                        .HasColumnType("int");

                    b.Property<decimal>("DocumentationScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("EfficiencyScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluatorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProblemSolvingScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("QualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ReworkHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TimelinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UnauthorizedDeviationScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId")
                        .IsUnique();

                    b.ToTable("TaskEvaluations");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptanceCriteria")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("AlternativeAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovedAlternative")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("RequiredPath")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.Property<string>("WhatRequired")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId")
                        .IsUnique();

                    b.ToTable("TaskInstructions");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ActualPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AlternativePathApproved")
                        .HasColumnType("bit");

                    b.Property<int>("BusinessImpact")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PathApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RequiredPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskRisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExpectedLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Impact")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mitigation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("MitigationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Probability")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskRisks");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.CorrectionPlan", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.Employee", "Employee")
                        .WithMany("CorrectionPlans")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.MonthlyEvaluation", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.Employee", "Employee")
                        .WithMany("MonthlyEvaluations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.SalaryHistory", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.Employee", "Employee")
                        .WithMany("SalaryHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskBenefit", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.TaskItem", "TaskItem")
                        .WithOne("Benefit")
                        .HasForeignKey("EmployeeValueEvaluation.Models.TaskBenefit", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskCost", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.TaskItem", "TaskItem")
                        .WithOne("Cost")
                        .HasForeignKey("EmployeeValueEvaluation.Models.TaskCost", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskEvaluation", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.TaskItem", "TaskItem")
                        .WithOne("Evaluation")
                        .HasForeignKey("EmployeeValueEvaluation.Models.TaskEvaluation", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskInstruction", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.TaskItem", "TaskItem")
                        .WithOne("Instruction")
                        .HasForeignKey("EmployeeValueEvaluation.Models.TaskInstruction", "TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskItem", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskRisk", b =>
                {
                    b.HasOne("EmployeeValueEvaluation.Models.TaskItem", "TaskItem")
                        .WithMany("Risks")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.Employee", b =>
                {
                    b.Navigation("CorrectionPlans");

                    b.Navigation("MonthlyEvaluations");

                    b.Navigation("SalaryHistories");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("EmployeeValueEvaluation.Models.TaskItem", b =>
                {
                    b.Navigation("Benefit");

                    b.Navigation("Cost");

                    b.Navigation("Evaluation");

                    b.Navigation("Instruction");

                    b.Navigation("Risks");
                });
#pragma warning restore 612, 618
        }
    }
}
